catalog_name: mlops_dev
schema_name: louiswil


parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - fixed_acidity
  - volatile_acidity
  - citric_acid
  - residual_sugar
  - chlorides
  - free_sulfur_dioxide
  - total_sulfur_dioxide
  - density
  - pH
  - sulphates
  - alcohol


cat_features:
  - type


target: quality
